project_id = "ajslpwfjkpuznufxnajl"

[functions.capture-text]
verify_jwt = true

[functions.insights-home]
verify_jwt = true

[functions.export-data]
verify_jwt = true

[functions.export-pdf]
verify_jwt = true

[functions.delete-data]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.nudges]
verify_jwt = true

[functions.trends-data]
verify_jwt = true