// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajslpwfjkpuznufxnajl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqc2xwd2Zqa3B1em51ZnhuYWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTQyMDQsImV4cCI6MjA3MTQzMDIwNH0.vKLowAg4uer-pZeTe7aB6fA3Qn0VQE2IfrCGbbTv4pM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});